### ISSUE TITLE
video breakup

### ISSUE THREAD

**Issue by dbrooke** [myorangedragon/longmynd#20]
Testing with QO-100 beacon I had good results from a Portsdown streaming UDP to mplayer on my desktop PC but running LongMynd on the desktop resulted in video breakup both with UDP over loopback and longmynd_main_ts fifo.

I noticed that the LongMynd version on Portsdown was older and running that version on the desktop was fine.

I performed a git bisect which reveals that 96dfaf9be7b8dab148b977c150f241e596f515c3 is the first bad commit.

**Comment by philcrump** [comment]
Hi Dave! Interesting. This should really have no adverse effect as all it does is mean that thread comes out of sleep a little more often.

Can you give me more details on your setup on the desktop PC? Operating system version, and how much CPU longmynd was drawing?

**Comment by philcrump** [comment]
Thanks for the bisect, made finding this bug far easier than it would otherwise have been!

Fixed in #21

**Comment by dbrooke** [comment]
Hi Phil. No problem, it's the least I could do.

I can confirm that building from your phil-fix-tslock branch referenced in #21 fixes the problem for me too.

Thanks for the fix.
