### ISSUE TITLE
TS discontinuities

### ISSUE THREAD

**Issue by daniestevez** [myorangedragon/longmynd#22]
I'm watching the AMSAT-DL symposium on QO-100 today by streaming from longmynd to vlc (2Msym DVB-S2 QPSK 4/5). With the master revision I've found lots of TS discontinuities and other problems in vlc. This doesn't happen with older versions of longmynd. Using git bisect I've located the first bad commit to be 96dfaf9be7b8dab148b977c150f241e596f515c3. I'll look at this further after the conference, but I'm submitting the issue now so that I don't forget.

This also happens with the 1.5Msym beacon, so it is easy to replicate for me.

I see that #20 is very similar to this problem, but for me the current master doesn't work.

**Comment by daniestevez** [comment]
I now see that #21, which is the PR fixing for #20, was never merged to master. I confirm that applying the diff in #21 by hand on top of master fixes this problem, so I believe that #21 should be merge to master.

**Comment by philcrump** [comment]
Hi, FYI we've got a more actively maintained branch of longmynd with this and a few other fixes at https://github.com/BritishAmateurTelevisionClub/longmynd/ (this is the version used in the BATC Portsdown & Ryde projects)

**Comment by daniestevez** [comment]
Thanks! I didn't know about the BATC fork. I confirm that the master in there works fine for me.

**Comment by philcrump** [comment]
Of course when I cleaned out all my old branches from my fork it had the unintended (and un-notified) effect of closing out the pending PRs here... I'll fix that as we've never intended not to upstream it all.

BTW will be testing some new longmynd changes by watching your AMSAT-DL talk later!

**Comment by daniestevez** [comment]
Closing, since the BATC fork works. I probably forgot to close this back in the day.
